
version: 2

models:
  - name: raw_customers
    description: "A CTE Customer dbt model"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: first_name
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: last_name
        description: "The primary key for this table"
        data_tests:
          - not_null
  - name: customers_dashboard
    description: "A Customer dbt model"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null